/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Metodos.MetodosBD;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JoaN
 */
public class prestamosVisualizar extends javax.swing.JFrame {

    /**
     * Creates new form pelisBuscar
     */
    public prestamosVisualizar() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cboxFiltro = new javax.swing.JComboBox();
        txtBusqueda = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBusquedaMod = new javax.swing.JTextField();
        botonModificar = new javax.swing.JButton();
        txtPeliculaModificado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFechaModificado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioModificado = new javax.swing.JTextField();
        rellenar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtDiasModificado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Socio", "Codigo Pelicula", "Fecha Prestamo", "Precio", "Dias Prestamo"
            }
        ));
        tablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDatos);

        jLabel1.setText("Buscar por:");

        cboxFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Numero Socio", "Codigo Pelicula", "Fecha Prestamo", "Precio", "Dias Prestamo" }));

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero Socio");

        botonModificar.setText("Modificar");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        txtPeliculaModificado.setEditable(false);
        txtPeliculaModificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeliculaModificadoActionPerformed(evt);
            }
        });

        jLabel4.setText("Codigo Pelicula");

        jLabel5.setText("Fecha Prestamo");

        txtFechaModificado.setEditable(false);
        txtFechaModificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaModificadoActionPerformed(evt);
            }
        });

        jLabel6.setText("Precio");

        txtPrecioModificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioModificadoActionPerformed(evt);
            }
        });

        rellenar.setText("Rellenar");
        rellenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rellenarActionPerformed(evt);
            }
        });

        jLabel8.setText("Dias Prestamo");

        txtDiasModificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiasModificadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusquedaMod, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(rellenar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(32, 32, 32)
                                .addComponent(txtPeliculaModificado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32)
                                .addComponent(txtFechaModificado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(32, 32, 32)
                                .addComponent(txtPrecioModificado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(32, 32, 32)
                                .addComponent(txtDiasModificado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBusquedaMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificar)
                    .addComponent(rellenar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPeliculaModificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFechaModificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrecioModificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDiasModificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    MetodosBD metodosbd = new MetodosBD();
    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
       metodosbd.BuscarPrestamos(txtBusqueda.getText(), cboxFiltro.getSelectedItem().toString(), tablaDatos);
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        int exito=0;
        
        String pelicula="";
        //System.out.println("Fecha: "+txtFechaModificado.getText() + "Titulo: "+txtTituloModificado.getText());
        
        Double precio=Double.parseDouble(txtPrecioModificado.getText());
        Integer dias=Integer.parseInt(txtDiasModificado.getText());
        pelicula=txtPeliculaModificado.getText();
        java.sql.Date sqlDate=null;
        String fecha=txtFechaModificado.getText();
        if(fecha.equals("")){
            //System.out.println("Fecha: "+fecha);
        }else{
            SimpleDateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date invoiceDate = null;
            try {

                    invoiceDate = formatDate.parse(fecha);
            } catch (ParseException ex) {
                    Logger.getLogger(pelisVisualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            sqlDate = new java.sql.Date(invoiceDate.getTime());
            //System.out.println("sqlDate= "+sqlDate);
        }
       
        
        
        
        exito = metodosbd.ModificarPrestamos(txtBusquedaMod.getText(), pelicula, sqlDate, precio, dias);
        
        if(exito>0){
            JOptionPane.showMessageDialog(null, "Los datos se han actualizado correctamente", 
                    "Exito en la operacion",JOptionPane.INFORMATION_MESSAGE);
            metodosbd.BuscarPrestamos(txtBusqueda.getText(), cboxFiltro.getSelectedItem().toString(), tablaDatos);
        }else{
            JOptionPane.showMessageDialog(null, "Los datos no se pudieron actualizar", 
                    "Error en la operacion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonModificarActionPerformed

    private void txtPeliculaModificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeliculaModificadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeliculaModificadoActionPerformed

    private void txtPrecioModificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioModificadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioModificadoActionPerformed

    private void rellenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rellenarActionPerformed
        int fila=tablaDatos.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null,"Por favor, seleccione una fila"); 
        }else{
            //System.out.println("fila: "+fila);
            String socio=(String)tablaDatos.getValueAt(fila, 0);
            //System.out.println("id: "+id);
            txtBusquedaMod.setText(socio);
            String peli=(String)tablaDatos.getValueAt(fila, 1);
            txtPeliculaModificado.setText(peli);
            String fecha=(String)tablaDatos.getValueAt(fila, 2);
            txtFechaModificado.setText(fecha);
            String precio=(String)tablaDatos.getValueAt(fila, 3);
            txtPrecioModificado.setText(precio);
            String dias=(String)tablaDatos.getValueAt(fila, 4);
            txtDiasModificado.setText(dias);
            
        }
        
    }//GEN-LAST:event_rellenarActionPerformed

    private void tablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatosMouseClicked
        int fila=tablaDatos.getSelectedRow();
       
           //System.out.println("fila: "+fila);
            String socio=(String)tablaDatos.getValueAt(fila, 0);
            //System.out.println("id: "+id);
            txtBusquedaMod.setText(socio);
            String peli=(String)tablaDatos.getValueAt(fila, 1);
            txtPeliculaModificado.setText(peli);
            String fecha=(String)tablaDatos.getValueAt(fila, 2);
            txtFechaModificado.setText(fecha);
            String precio=(String)tablaDatos.getValueAt(fila, 3);
            txtPrecioModificado.setText(precio);
            String dias=(String)tablaDatos.getValueAt(fila, 4);
            txtDiasModificado.setText(dias);
        
    }//GEN-LAST:event_tablaDatosMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Prestamos abrir = new Prestamos();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void txtDiasModificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiasModificadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiasModificadoActionPerformed

    private void txtFechaModificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaModificadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaModificadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prestamosVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prestamosVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prestamosVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prestamosVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prestamosVisualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JComboBox cboxFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rellenar;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtBusquedaMod;
    private javax.swing.JTextField txtDiasModificado;
    private javax.swing.JTextField txtFechaModificado;
    private javax.swing.JTextField txtPeliculaModificado;
    private javax.swing.JTextField txtPrecioModificado;
    // End of variables declaration//GEN-END:variables
}
