/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author JoaN
 */
import Metodos.ConexionMySQL;
import java.sql.*; 
import javax.swing.JOptionPane;
public class primerForm extends javax.swing.JFrame {
    
    /**
     * Creates new form primerForm
     */
    public primerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPeliculas = new javax.swing.JDialog();
        peliBorrar = new javax.swing.JButton();
        peliInsertar = new javax.swing.JButton();
        peliModificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSocios = new javax.swing.JDialog();
        jPrestamos = new javax.swing.JDialog();
        jPeliInsertar = new javax.swing.JDialog();
        jPeliBorrar = new javax.swing.JDialog();
        jPeliModificar = new javax.swing.JDialog();
        prestamos = new javax.swing.JButton();
        socios = new javax.swing.JButton();
        peliculas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        conectar = new javax.swing.JButton();

        jPeliculas.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        peliBorrar.setText("Borrar");
        peliBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliBorrarActionPerformed(evt);
            }
        });
        jPeliculas.getContentPane().add(peliBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        peliInsertar.setText("Insertar");
        peliInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliInsertarActionPerformed(evt);
            }
        });
        jPeliculas.getContentPane().add(peliInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        peliModificar.setText("Modificar");
        peliModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliModificarActionPerformed(evt);
            }
        });
        jPeliculas.getContentPane().add(peliModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 119, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("PELICULAS");
        jPeliculas.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 190, -1));

        javax.swing.GroupLayout jSociosLayout = new javax.swing.GroupLayout(jSocios.getContentPane());
        jSocios.getContentPane().setLayout(jSociosLayout);
        jSociosLayout.setHorizontalGroup(
            jSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jSociosLayout.setVerticalGroup(
            jSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPrestamosLayout = new javax.swing.GroupLayout(jPrestamos.getContentPane());
        jPrestamos.getContentPane().setLayout(jPrestamosLayout);
        jPrestamosLayout.setHorizontalGroup(
            jPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPrestamosLayout.setVerticalGroup(
            jPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPeliInsertarLayout = new javax.swing.GroupLayout(jPeliInsertar.getContentPane());
        jPeliInsertar.getContentPane().setLayout(jPeliInsertarLayout);
        jPeliInsertarLayout.setHorizontalGroup(
            jPeliInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPeliInsertarLayout.setVerticalGroup(
            jPeliInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPeliBorrarLayout = new javax.swing.GroupLayout(jPeliBorrar.getContentPane());
        jPeliBorrar.getContentPane().setLayout(jPeliBorrarLayout);
        jPeliBorrarLayout.setHorizontalGroup(
            jPeliBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPeliBorrarLayout.setVerticalGroup(
            jPeliBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPeliModificarLayout = new javax.swing.GroupLayout(jPeliModificar.getContentPane());
        jPeliModificar.getContentPane().setLayout(jPeliModificarLayout);
        jPeliModificarLayout.setHorizontalGroup(
            jPeliModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPeliModificarLayout.setVerticalGroup(
            jPeliModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prestamos.setText("PRESTAMOS");
        prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamosActionPerformed(evt);
            }
        });
        getContentPane().add(prestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        socios.setText("SOCIOS");
        socios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sociosActionPerformed(evt);
            }
        });
        getContentPane().add(socios, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        peliculas.setText("PELICULAS");
        peliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliculasActionPerformed(evt);
            }
        });
        getContentPane().add(peliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("PROYECTO VIDEOCLUB");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 320, 20));

        jLabel3.setText("Conectar a la base de datos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        conectar.setText("Conectar");
        conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarActionPerformed(evt);
            }
        });
        getContentPane().add(conectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sociosActionPerformed
        jSocios.setVisible(true);
    }//GEN-LAST:event_sociosActionPerformed

    private void peliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliculasActionPerformed
        jPeliculas.setVisible(true);
    }//GEN-LAST:event_peliculasActionPerformed

    private void peliInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliInsertarActionPerformed
        jPeliculas.setVisible(false);
        jPeliInsertar.setVisible(true);
    }//GEN-LAST:event_peliInsertarActionPerformed

    private void prestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamosActionPerformed
        jPrestamos.setVisible(true);
    }//GEN-LAST:event_prestamosActionPerformed

    private void peliBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliBorrarActionPerformed
        jPeliculas.setVisible(false);
        jPeliBorrar.setVisible(true);
    }//GEN-LAST:event_peliBorrarActionPerformed

    private void peliModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliModificarActionPerformed
        jPeliculas.setVisible(false);
        jPeliModificar.setVisible(true);
    }//GEN-LAST:event_peliModificarActionPerformed

    private void conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectarActionPerformed
         ConexionMySQL mysql = new ConexionMySQL();
        
        java.sql.Connection cn = mysql.Conectar();
        
        if(!cn.equals(null)){
            JOptionPane.showMessageDialog(null, "Conectado");
            
            try{
                cn.close();
            }catch(SQLException ex){
                System.out.println("Error al desconectar");
            }
            
            
        }
    }//GEN-LAST:event_conectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(primerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(primerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(primerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(primerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new primerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conectar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JDialog jPeliBorrar;
    private javax.swing.JDialog jPeliInsertar;
    private javax.swing.JDialog jPeliModificar;
    private javax.swing.JDialog jPeliculas;
    private javax.swing.JDialog jPrestamos;
    private javax.swing.JDialog jSocios;
    private javax.swing.JButton peliBorrar;
    private javax.swing.JButton peliInsertar;
    private javax.swing.JButton peliModificar;
    private javax.swing.JButton peliculas;
    private javax.swing.JButton prestamos;
    private javax.swing.JButton socios;
    // End of variables declaration//GEN-END:variables
}
